DATABASE_FILE = 'test.sqlite'
NUM_REPETITIONS = 1
NUM_SIMULATORS = 1
NUM_PARALLEL_PROCESSES = 1
ENVIRONMENT = 'noisy'

POPULATION_SIZE = 4
OFFSPRING_SIZE = 2
NUM_GENERATIONS = 500

LEARN_POPULATION_SIZE = 4
LEARN_NUM_GENERATIONS = 2
SCALING_FACTOR = 0.5

PARENT_SELECT_STRATEGY = 'tournament'
PARENT_TOURNAMENT_SIZE = 4
SURVIVOR_SELECT_STRATEGY = 'best'

INIT_MIN_MODULES = 15
INIT_MAX_MODULES = 20
MAX_NUMBER_OF_MODULES = 20
MAX_ADD_MODULES = 2
MAX_DELETE_MODULES = 2