#Configurations for each experiments.

MAX_NUMBER_OF_MODULES = 20

#Tournament?
PARENT_TOURNAMENT_SIZE = 5
POPULATION_SIZE = 200
OFFSPRING_SIZE = 20
FUNCTION_EVALUATIONS = 600000
LOCAL_COMPETITION_NEIGHBOURHOOD_SIZE = 10

PARENT_SELECT_STRATEGY = 'tournament'


#gene generator
CHANCETOPLACECORE = 0.6 # Chance to place a block for each possible location.
CHANCETOPLACEBRICK = 0.25
MAX_BRICKS = 20