#Configurations for each experiments.
LOG_FOLDER = "./experiments/"


#EA
PARENT_TOURNAMENT_SIZE = 5
POPULATION_SIZE = 20
OFFSPRING_SIZE = 20
FUNCTION_EVALUATIONS = 600
LOCAL_COMPETITION_NEIGHBOURHOOD_SIZE = 10
MUTATION_RATE = 0.05
CROSSOVER_RATE = 1.0
CROSSOVER_CHANCE_TO_DIVE = 0.5
PARENT_SELECT_STRATEGY = 'tournament'





#gene generator
CHANCE_TO_PLACE_CORE = 0.6 # Chance to place a block for each possible location.
CHANCE_TO_PLACE_BRICK_FRONT = 0.8
CHANCE_TO_PLACE_BRICK_SIDES = 0.3
CHANCE_TO_ROTATE = 0.25
MAX_BRICKS = 30


# Brain

BRAIN_MUTATION_RATE = 0.5
INNER_LOOP_ITERATIONS = 2
EXPLORATION_RATE = 1
MUTATION_EPSILON = 0.7

