#Configurations for each experiments.
LOG_FOLDER = "/experiments/"


#EA
PARENT_TOURNAMENT_SIZE = 5
POPULATION_SIZE = 20
OFFSPRING_SIZE = 20
FUNCTION_EVALUATIONS = 600
LOCAL_COMPETITION_NEIGHBOURHOOD_SIZE = 10
MUTATION_RATE = 0.05
CROSSOVER_RATE = 1.0
PARENT_SELECT_STRATEGY = 'tournament'


#gene generator
CHANCE_TO_PLACE_CORE = 0.6 # Chance to place a block for each possible location.
CHANCE_TO_PLACE_BRICK = 0.6
CHANCE_TO_ROTATE = 0.25
MAX_BRICKS = 15


# Brain

BRAIN_MUTATION_RATE = 0.5

